=== archanadalvi27/TestGitPOC/DCAE_mS1_Test/target/test-classes/Schema_FlatironTopology_27.1.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {},
    "id": "http://example.com/example.json",
    "properties": {
        "_flatironUpdateTimeMs": {
            "id": "/properties/_flatironUpdateTimeMs",
            "type": "integer"
        },
        "alias": {
            "id": "/properties/alias",
            "type": "string"
        },
        "cdate": {
            "id": "/properties/cdate",
            "type": "string"
        },
        "class": {
            "id": "/properties/class",
            "type": "string"
        },
        "clli": {
            "id": "/properties/clli",
            "type": "string"
        },
        "communityString": {
            "id": "/properties/communityString",
            "type": "string"
        },
        "customerName": {
            "id": "/properties/customerName",
            "type": "string"
        },
        "deviceType": {
            "id": "/properties/deviceType",
            "type": "string"
        },
        "domain": {
            "id": "/properties/domain",
            "type": "string"
        },
        "entityType": {
            "id": "/properties/entityType",
            "type": "string"
        },
        "equipVendor": {
            "id": "/properties/equipVendor",
            "type": "string"
        },
        "equip_vendor_model": {
            "id": "/properties/equip_vendor_model",
            "type": "string"
        },
        "fqdn": {
            "id": "/properties/fqdn",
            "type": "string"
        },
        "functionCode": {
            "id": "/properties/functionCode",
            "type": "string"
        },
        "globalCustomerId": {
            "id": "/properties/globalCustomerId",
            "type": "string"
        },
        "inMaint": {
            "id": "/properties/inMaint",
            "type": "string"
        },
        "inmsList": {
            "id": "/properties/inmsList",
            "type": "string"
        },
        "isManaged": {
            "id": "/properties/isManaged",
            "type": "string"
        },
        "mdate": {
            "id": "/properties/mdate",
            "type": "string"
        },
        "name": {
            "id": "/properties/name",
            "type": "string"
        },
        "network": {
            "id": "/properties/network",
            "type": "string"
        },
        "oamIpv6": {
            "id": "/properties/oamIpv6",
            "type": "string"
        },
        "oid": {
            "id": "/properties/oid",
            "type": "string"
        },
        "osType": {
            "id": "/properties/osType",
            "type": "string"
        },
        "osVersion": {
            "id": "/properties/osVersion",
            "type": "string"
        },
        "provStatus": {
            "id": "/properties/provStatus",
            "type": "string"
        },
        "service": {
            "id": "/properties/service",
            "type": "string"
        },
        "serviceId": {
            "id": "/properties/serviceId",
            "type": "string"
        },
        "source": {
            "id": "/properties/source",
            "type": "string"
        },
        "transactionId": {
            "id": "/properties/transactionId",
            "type": "string"
        },
        "transactionTimeStamp": {
            "id": "/properties/transactionTimeStamp",
            "type": "string"
        },
        "uuid": {
            "id": "/properties/uuid",
            "type": "string"
        }
    },
    "type": "object"
}

=== archanadalvi27/TestGitPOC/DCAE_mS1_Test/target/classes/flatiron_vNF.json
{
    "functionCode": "ctbe",
    "clli": "LSLEILAA",
    "inmsList": "",
    "oid": "ctbe0002vm003",
    "_flatironUpdateTimeMs": 1502460520129,
    "source": "/opt/app/cambria/anaidata/process/AnAI_Device.raw-2017081105",
    "uuid": "f0c693e6-a091-4096-9184-bef7af08ede9",
    "network": "CBB",
    "osVersion": "Proprietary",
    "equip_vendor_model": "R202-May27",
    "osType": "Proprietary",
    "alias": "ctbe0002vm003",
    "serviceId": "e433710f-9217-458d-a79d-1c7aff376d89",
    "class": "Device",
    "equipVendor": "Nokia",
    "oamIpv6": "",
    "deviceType": "VM",
    "fqdn": "",
    "entityType": "vserver",
    "transactionTimeStamp": "20170811-14:08:39:599",
    "globalCustomerId": "",
    "customerName": "",
    "transactionId": "76aa9d45-8f0e-4e76-aa60-e311cf33ef2e",
    "isManaged": "true",
    "cdate": "Tue Jun 13 10:37:46 CDT 2017",
    "provStatus": "",
    "mdate": "Fri Aug 11 09:08:40 CDT 2017",
    "communityString": "",
    "service": "VOIP-VUSP",
    "domain": "e2e1",
    "inMaint": "false",
    "name": "ctbe0002vm003"
}
